repo_manage.py: bug fix on function remove_repo of class RepoMgr
Fix 8550b600b05d839. A single quote in wrong posithin may cause
an exeption as below:
ValueError: unsupported format character ''' (0x27) at index 27

'%'s Vs '%s'

Story: 2008862
Task: 45010

Test Plan:
Pass: Remove repo does not exist

Signed-off-by: ZhangXiao <xiao.zhang@windriver.com>
Change-Id: I9f3c9606470a83754a3d21f396a9547018855b46