Debian: build-pkgs: Fixed the issue of removing 'sign' type
Fixed the issue that wrong way is used to remove the
build type 'sign' from the list build_types.

Story: 2008846
Task: 45614

Test Plan:
Pass: build -c -l distro
      There should be no error like below:
      "del build_types['sign']
      TypeError: list indices must be integers or slices, not str"

Signed-off-by: Haiqing Bai <haiqing.bai@windriver.com>
Change-Id: I9dbb89b38c7e198428d20d43805ca637011f6146